services:
  # Development environment
  dev:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ./src/jsonDataBuilder:/usr/share/nginx/html/
      # - ./src/jsonDataBuilder/media/*.*:/usr/share/nginx/html/media/

    environment:
      - NGINX_ENV=development
    restart: unless-stopped
    networks:
      - blueaura-network

  # Production environment
  prod:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    environment:
      - NGINX_ENV=production
    restart: always
    networks:
      - blueaura-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  blueaura-network:
    driver: bridge